### ISSUE TITLE
post-migration script doesn't handle missing modern name

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.images#27]
When there is a missing or blank modern-name element in meta.xml, the post-migration script blows up:

```
ERROR, UNEXPECTED EXCEPTION
'modern-name'
Traceback (most recent call last):
  File "bin/post-migrate.py", line 91, in <module>
    main(args)
  File "bin/post-migrate.py", line 28, in inner
    return func(*args, **kwargs)
  File "bin/post-migrate.py", line 47, in main
    pkg.open(os.path.join(real_path,d))
  File "/home/paregorios/Documents/i/isaw.images/bin/../isaw/images/arglogger.py", line 18, in inner
    return func(*args, **kwargs)
  File "/home/paregorios/Documents/i/isaw.images/bin/../isaw/images/package.py", line 238, in open
    self.make_overview()
  File "/home/paregorios/Documents/i/isaw.images/bin/../isaw/images/arglogger.py", line 18, in inner
    return func(*args, **kwargs)
  File "/home/paregorios/Documents/i/isaw.images/bin/../isaw/images/package.py", line 357, in make_overview
    text = ['', geo['modern-name']]['modern-name' in geo.keys()]
KeyError: 'modern-name'
```

**Comment by paregorios** [comment]
I'm working on this in branch issue27
